<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Wink</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!--<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/css/bootstrap-combined.min.css" rel="stylesheet">-->
   
    <link href="<?php echo $this->asset('assets/css/bootstrap_modif.css') ?>" rel="stylesheet">
     <link href="<?php echo $this->asset('assets/css/tuiles.css') ?>" rel="stylesheet">
    
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js"></script>
    <script type="text/javascript" src=<?php echo $this->asset('assets/js/eegg.js') ?>></script>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <?php if ($this['atomik.debug'] && Atomik::isPluginLoaded('DebugBar')) echo $this->renderDebugBarHead(); ?>
  </head>
  <body>
    <div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#"><img class="logo" src="<?php echo $this->asset('assets/images/logo-wink.png') ?>" ></a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="?action=accueil">Accueil</a></li>
      <?php $auth = Atomik::get('session.login');
      if (isset ($auth)) {?>
     	 <li><a href="?action=moncompte">Mon profil</a></li>
     <?php }?>
    </ul>
    <!--<form class="navbar-form navbar-left">
      <input type="text" class="form-control col-lg-8" placeholder="Search">
    </form>-->
    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <span class="glyphicon glyphicon-cog"></span> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Mon compte</a></li>
          <li class="divider"></li>
          <li><a href="?action=logout">Déconnexion</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>
    <div class="container">
      <?php if (count($this['flash_messages'])): ?>
        <?php foreach ($this['flash_messages'] as $label => $messages): ?>
          <?php foreach ($messages as $message): ?>
            <div class="alert alert-<?php echo $label ?>"><?php echo $message ?></li>
          <?php endforeach; ?>
        <?php endforeach; ?>
      <?php endif ?>
    
      <div id="content">
        <?php echo $contentForLayout; ?>
      </div>
    </div>
    <?php if ($this['atomik.debug'] && Atomik::isPluginLoaded('DebugBar')) echo $this->renderDebugBar(); ?>
  </body>
</html>
