
<div class="container" >
	<div class="tuile-center" id="main">
	</div>
</div>




 <!-- Modal -->
<div class="modal fade" id="modal_match" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">C'est un match !</h4>
      </div>
      <div class="modal-body">
        <p id="modal_match_body"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>







<script type="text/javascript" src=<?php echo $this->asset('assets/js/send_Wink.js') ?>></script>
<script type="text/javascript" src=<?php echo $this->asset('assets/js/get_profiles.js') ?>></script>