 <link href="<?php echo $this->asset('assets/css/accueil.css') ?>" rel="stylesheet">

<div class="accueil">
      <div class="accueil-logo">
        <a href=""></a>
      </div>
      <div class="row">
        <div class="col-lg-5 col-md-4 col-sm-4 col-xs-2"></div>
        <div class="co-cas col-lg-2 col-md-4 col-sm-4 col-xs-8"><a href="?action=login"><button type="button" class="btn btn-primary btn-lg">Connexion CAS</button></a></div>
        <div class="col-lg-5 col-md-4 col-sm-4 col-xs-2"></div>
      </div>
    </div>