<div class="hero-unit">
  <h1>Welcome to <strong>PLANC'UTC</strong></h1>
  <p>
   Le site de rencontre pour Utcéens exigeants !
    <a href="http://atomikframework.com/docs/get-started.html">Get Started</a> tutorial.
  </p>
  <p><a class="btn btn-large" href="http://atomikframework.com/docs">Read the documentation &raquo;</a></p>
</div>

<div class="row">

    <div class="span2">
        <h2>Modifier mes informations personnelles</h2>

        <form action="?action=infos_profil&function=update" method="post">
        	<label id="telephone">Telephone :</label><input type="text" name="telephone" id="telephone" value=<?php if (isset ($infos['infos_profil']['tel'])) echo ("0" . $infos['infos_profil']['tel']);?>>
        	<label id="adresse">Adresse : </label>
        	<select name="adresse">
        		<?php 
        		echo("<option value='".$infos['infos_profil']['id']."'>".$infos['infos_profil']['nom']."</option>");
        			foreach ($infos['quartier'] as $i)
        					echo("<option>".$i['nom']."</option>");?>
        	</select>
        	<INPUT TYPE="submit" VALUE="Valider">
        </form>
        
    </div>
   
</div>
