<div class="hero-unit">
  <h1>Welcome to <strong>PLANC'UTC</strong></h1>
  <p>
   Le site de rencontre pour Utcéens exigeants !
    <a href="http://atomikframework.com/docs/get-started.html">Get Started</a> tutorial.
  </p>
  <p><a class="btn btn-large" href="http://atomikframework.com/docs">Read the documentation &raquo;</a></p>
</div>

<div class="row">

    <div class="span2">
        <h2>Modifier mes informations personnelles</h2>
		<div class="form-group">
        <form action="?action=infos_profil&function=update" method="post">
        	<label class="control-label" for="focusedInput">Telephone :</label><input type="text" class="form-control" id="focusedInput" name="telephone" id="telephone" value=<?php if (isset ($infos['infos_profil']['tel'])) echo ("0" . $infos['infos_profil']['tel']);?>>
        	<label class="control-label" for="focusedInput" id="adresse">Adresse : </label>
        	<select class="form-control" id="select" name="adresse">
        		<?php 
        		echo("<option value='".$infos['infos_profil']['nom']."'>".$infos['infos_profil']['nom']."</option>");
        			foreach ($infos['quartier'] as $i)
        					echo("<option>".$i['nom']."</option>");?>
        	</select>
        	<label class="control-label" for="focusedInput" id="semestre">Semestre d'etude actuel</label><input class="form-control" id="focusedInput" type="text" name="semestre" id="semestre" value=<?php if (isset ($infos['infos_profil']['semestre'])) echo ($infos['infos_profil']['semestre']);?>>
        	<INPUT TYPE="submit" VALUE="Valider" class="btn btn-default">
        </form>
        </div>
    </div>
   
</div>
