<div class="hero-unit">
  <h1>Welcome to <strong>PLANC'UTC</strong></h1>
  <p>
   Le site de rencontre pour Utcéens exigeants !
    <a href="http://atomikframework.com/docs/get-started.html">Get Started</a> tutorial.
  </p>
  <p><a class="btn btn-large" href="http://atomikframework.com/docs">Read the documentation &raquo;</a></p>
</div>

<div class="row">

    <div class="span2">
        <h2>Modifier mes informations personnelles</h2>
        <form action="modif_info_profil">
        	<label id="telephone">Telephone :</label><input type="text" id="telephone">
        	<label id="email">Email :</label><input  type="email" id="email">
        	<label id="adresse">Adresse : </label><textarea id="adresse"></textarea>
        </form>
        
    </div>
   
</div>
