
<h2>Bienvenue <?php echo Atomik::get('session.login');?></h2>

<div class="row"> 
<?php if (isset ($compte)) {?>
	<ul class="list-group col-lg-7" >
	  <li class="list-group-item"><span class="badge">Nom</span><?php echo $compte['etudiant']['nom'];?></li>
	  <li class="list-group-item"><span class="badge">Prénom</span><?php echo $compte['etudiant']['prenom'];?></li>
	  <li class="list-group-item"><span class="badge">Age</span><?php echo $compte['infos_profil']['age'];?></li>
	  <li class="list-group-item"><span class="badge">Sexe</span><?php echo $compte['infos_profil']['sexe'];?></li>
	  <li class="list-group-item"><span class="badge">Email</span><?php echo $compte['etudiant']['email'];?></li>
	  <li class="list-group-item"><span class="badge">Semestre</span><?php echo $compte['infos_profil']['semestre'];?></li>
	  <li class="list-group-item"><span class="badge">Orientation</span><?php echo $compte['infos_profil']['orientation'];?></li>
	  <li class="list-group-item"><span class="badge">Localisation</span><?php echo $compte['quartier']['nom'];?></li>
	
	<form action="?action=infos_profil" method="post" >
	      <INPUT TYPE="submit" VALUE="Modifier profil" class="btn btn-default">
	</form>
	</ul>
	<?php }?>

	<div class="list-group col-lg-3">
<?php  echo "<img src=\"assets/images/profile_picture/".$compte['image']['source']."\"/>"?>
 	</div>
 </div>   