


<?php
if (!isset($_POST['MODCASID']))
{
			echo 'Pour récupérer la liste des fichiers *.edt, il faut le cookie MODCASID.<br/>
				Pour avoir ce cookie, allez <a href="http://wwwetu.utc.fr/sme/EDT/">ici</a><br/>
				<form method="POST" action="">
					<label for="MODCASID">MODCASID : </label><input type="text" id="MODCASID" size="32" name="MODCASID" />
					<input type="submit" />
			</form>';
}
else
{

}

?>