  <div class="row">
    <div class="col-md-8">
	<form class="form-horizontal">
		<h1>Bienvenue sur Wink</h1>
                 

                   <div class="form-group">
            <label class="col-md-4 control-label" for="textinput">Je suis un(e) </label>
            <div class="col-sm-8">
             <select class="form-control" id="select">
                        <option>Homme</option>
                        <option>Femme</option>
                      </select>
            </div>
          </div>

           <div class="form-group">
            <label class="col-md-4 control-label" for="textinput">Intéressé(e) par </label>
            <div class="col-sm-8">
             <select class="form-control" id="select">
                        <option>Homme</option>
                        <option>Femme</option>
                         <option>Les deux</option>
                      </select>
            </div>
          </div>


                  <div class="form-group">
                  	<div class="pull-right">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button type="submit" class="btn btn-primary">Suivant</button>
                    </div>
                </div>
                  </div>

              </form>
</div>
</div>
